## NUMPY
Numerical python. this library give us multy dimension arrays

 # why numpy?
 1. memory requirement less 
 2. time execution is high
 3. Easy to use
 

### Numpy array
it cannt have elements of different data types

In [4]:
import numpy as np

a=[1,2,3,4,5,6]
b=np.array(a)  #built-in array function
print(b)
print(type(b))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


# More function to create Numpy array
1. np.ones()
2. np.zeros()
3. np.full()
4. np.empty()


In [9]:
#np.ones()- array having element=1
b=np.ones(3)
b

array([1., 1., 1.])

In [10]:
b=np.ones(3,dtype=int)
b

array([1, 1, 1])

In [13]:
b=np.ones((2,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
#np.zeros()-where array having element 0
b=np.zeros(3)
b

array([0., 0., 0.])

In [12]:
b=np.zeros(3,dtype=int)
b

array([0, 0, 0])

In [14]:
b=np.zeros((3,4),dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
#np.full()
b=np.full(3,dtype=int)
b

TypeError: full() missing 1 required positional argument: 'fill_value'

In [7]:
b=np.full((3,5),2,dtype=float)
b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

## Some more function for creating NumPy array
### 1. np.arange()
### 2. np.linspace()


In [30]:
#arange()
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b=np.arange(2,10)         #(start,end)
b 

array([2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
b=np.arange(2,20,2)         #(start,end,difference)
b 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
#linspace()
b=np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [34]:
b=np.linspace(2,10,5)         #(start,end,number of values)
b 

array([ 2.,  4.,  6.,  8., 10.])

## More functions

In [36]:
b=np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
b=np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
b=np.random.rand(3)
b

array([0.73081484, 0.16948751, 0.89145674])

## Indexing and Slicing

In [16]:
import numpy as np
li=[1,2,3,4,5]
arr=np.array(li)
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [17]:
print(li[3])
print(arr[3])

4
4


In [19]:
print(li[1:4])
print(arr[1:4])

[2, 3, 4]
[2 3 4]


In [15]:
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li_2d)
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


In [20]:
print(li_2d[2][1])
print(arr_2d[2][1])

10
10


In [21]:
print(arr_2d[2,1])

10


In [22]:
print(li_2d[1][0:3])

[5, 6, 7]


In [23]:
print(arr_2d[1,0:3])

[5 6 7]


## MATHEMATICAL OPERATIONS

In [28]:
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)


In [31]:
#if i want add 1 in each element of array using NUMPY. 
a=a+1
a

array([ 9, 19, 17, 11,  7])

In [34]:
#Adding two numpy array
c=a+b
c

array([12, 20, 28, 13, 18])

In [36]:
#a to the power b
d=a**b
d

array([        729,          19, -1942714447,         121,  1977326743],
      dtype=int32)

In [38]:
#sum of array
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())#index of minimum element

63
12.6
7
4


In [39]:
a>b

array([ True,  True,  True,  True, False])

In [40]:
a==b

array([False, False, False, False, False])

In [41]:
a<b

array([False, False, False, False,  True])

In [42]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


   ## BOLEAN INDEXING

In [46]:
a=np.array(['t','b','r','d''e','f','z','a'])
b=np.random.randint(1,20,8)
b>10

array([ True,  True,  True,  True, False, False, False, False])

In [45]:
bool_arr=b>10
print(bool_arr)
new_arr=b[bool_arr]
print(new_arr)

[False  True  True  True False False False False]
[19 13 18]


In [47]:
new_arr=b[b>10]
new_arr

array([17, 11, 17, 17])

In [48]:
c=b
c

array([17, 11, 17, 17,  1,  2,  9,  4])

In [49]:
c[:3]=19
print(c)

[19 19 19 17  1  2  9  4]


In [50]:
c[c>15]=100
c

array([100, 100, 100, 100,   1,   2,   9,   4])

## np.where()

In [51]:
ind=np.where(b==100)
ind


(array([0, 1, 2, 3], dtype=int64),)

In [53]:
print(a)
print(b)
print(a[ind])

['t' 'b' 'r' 'de' 'f' 'z' 'a']
[100 100 100 100   1   2   9   4]
['t' 'b' 'r' 'de']


## Numpy brodcasting- 
describe how numpy treat unequal size array.

describing two elemt as compatible for operations:
1. dimension should be equal (x[3][2] and y[3][2])
2. one of them is 1 (x[3][3] and y[1][3])

In [55]:
import numpy as np
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print(y)

[[2 4 2]
 [7 6 6]
 [8 8 9]]
[[2 3 4]
 [1 8 3]
 [9 4 9]]


In [57]:
ans=x-y
ans

array([[ 0,  1, -2],
       [ 6, -2,  3],
       [-1,  4,  0]])

In [58]:
import numpy as np
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3))
print(x)
print(y)

[[5 3 6]
 [9 8 8]
 [8 4 1]]
[7 9 4]


In [60]:
ans=x-y
ans       #NO ERROR BECAUSE OF 2ND RULE OF COMPATIBILITY.

array([[-2, -6,  2],
       [ 2, -1,  4],
       [ 1, -5, -3]])

In [61]:
import numpy as np
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(2,3))
print(x)
print(y)

[[1 8]
 [1 3]
 [7 1]]
[[2 8 2]
 [7 8 8]]


In [62]:
ans=x-y
ans    #ERROR - Shape is not compatible

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [68]:
#to make it compatible.
#1. transpose 
y=np.transpose(y)
print(y)
ans=x-y
ans

[[2 7]
 [8 8]
 [2 8]]


array([[-1,  1],
       [-7, -5],
       [ 5, -7]])

In [72]:
#resize- to change size
print(y.resize(2,3))
y

None


array([[2, 2, 8],
       [8, 7, 8]])

In [73]:
#reshape- to change size of array
print(y.reshape(3,2))
y

[[2 2]
 [8 8]
 [7 8]]


array([[2, 2, 8],
       [8, 7, 8]])